query allJobApplications(
  $offset: Int,
  $keyword: String,
  $time: String,
  $jcat: Int,
  $jcity: Int) {
  countJobApplications
  allJobApplications(
    offset: $offset,
    keyword: $keyword,
    time: $time,
    jcat: $jcat,
    jcity: $jcity) {
    id
    title
    content
    slug
    categories {
      id
      name
    }
    company {
      id
      name
    }
    insertedAt
    updatedAt
  }
}
