query singleJobApplicationBySlug($slug: String!) {
  singleJobApplicationBySlug(slug: $slug) {
    id
    title
    content
    slug
    categories {
      id
      name
    }
    company {
      id
      name
    }
    insertedAt
    updatedAt
  }
}
