# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Api.Repo.insert!(%Api.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

import Comeonin.Bcrypt, only: [hashpwsalt: 1]

alias Api.Repo
alias Api.Accounts.User
alias Api.Categories.Category

now = Ecto.DateTime.utc;

User |> Repo.delete_all()
Api.Repo.insert!(
  %User{first_name: "admin", last_name: "", email: "acadmin@npune.com", password_hash: hashpwsalt("aqv7B7Mdmbgp0&Y3R"), is_admin: true}
)

Category |> Repo.delete_all()
Api.Repo.insert_all(
	# %Category{ name: "Accountancy", description: "Accountancy jobs" },
	Category, 
	[[name: "accountant", description: "Accountant", inserted_at: now, updated_at: now],
	[name: "actor", description: "Actor", inserted_at: now, updated_at: now],
	[name: "actuary", description: "Actuary", inserted_at: now, updated_at: now],
	[name: "adjudicator", description: "Adjudicator", inserted_at: now, updated_at: now],
	[name: "administrative assistant", description: "Administrative Assistant", inserted_at: now, updated_at: now],
	[name: "administrative services manager", description: "Administrative Services Manager", inserted_at: now, updated_at: now],
	[name: "advertising manager", description: "Advertising Manager", inserted_at: now, updated_at: now],
	[name: "advertising sales agent", description: "Advertising Sales Agent", inserted_at: now, updated_at: now],
	[name: "aerobics instructor", description: "Aerobics Instructor", inserted_at: now, updated_at: now],
	[name: "aerospace engineer", description: "Aerospace Engineer", inserted_at: now, updated_at: now],
	[name: "aerospace engineering technician", description: "Aerospace Engineering Technician", inserted_at: now, updated_at: now],
	[name: "agent", description: "Agent", inserted_at: now, updated_at: now],
	[name: "agricultural engineer", description: "Agricultural Engineer", inserted_at: now, updated_at: now],
	[name: "agricultural equipment operator", description: "Agricultural Equipment Operator", inserted_at: now, updated_at: now],
	[name: "agricultural grader", description: "Agricultural Grader", inserted_at: now, updated_at: now],
	[name: "agricultural inspector", description: "Agricultural Inspector", inserted_at: now, updated_at: now],
	[name: "agricultural manager", description: "", inserted_at: now, updated_at: now],
	[name: "agricultural sciences teacher", description: "", inserted_at: now, updated_at: now],
	[name: "agricultural sorter", description: "", inserted_at: now, updated_at: now],
	[name: "agricultural technician", description: "", inserted_at: now, updated_at: now],
	[name: "agricultural worker", description: "", inserted_at: now, updated_at: now],
	[name: "air conditioning installer", description: "", inserted_at: now, updated_at: now],
	[name: "air conditioning mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "air traffic controller", description: "", inserted_at: now, updated_at: now],
	[name: "aircraft cargo handling supervisor", description: "", inserted_at: now, updated_at: now],
	[name: "aircraft mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "aircraft service technician", description: "", inserted_at: now, updated_at: now],
	[name: "airline copilot", description: "", inserted_at: now, updated_at: now],
	[name: "airline pilot", description: "", inserted_at: now, updated_at: now],
	[name: "ambulance dispatcher", description: "", inserted_at: now, updated_at: now],
	[name: "ambulance driver", description: "", inserted_at: now, updated_at: now],
	[name: "amusement machine servicer", description: "", inserted_at: now, updated_at: now],
	[name: "anesthesiologist", description: "", inserted_at: now, updated_at: now],
	[name: "animal breeder", description: "", inserted_at: now, updated_at: now],
	[name: "animal control worker", description: "", inserted_at: now, updated_at: now],
	[name: "animal scientist", description: "", inserted_at: now, updated_at: now],
	[name: "animal trainer", description: "", inserted_at: now, updated_at: now],
	[name: "animator", description: "", inserted_at: now, updated_at: now],
	[name: "answering service operator", description: "", inserted_at: now, updated_at: now],
	[name: "anthropologist", description: "", inserted_at: now, updated_at: now],
	[name: "apparel patternmaker", description: "", inserted_at: now, updated_at: now],
	[name: "apparel worker", description: "", inserted_at: now, updated_at: now],
	[name: "arbitrator", description: "", inserted_at: now, updated_at: now],
	[name: "archeologist", description: "", inserted_at: now, updated_at: now],
	[name: "architect", description: "", inserted_at: now, updated_at: now],
	[name: "architectural drafter", description: "", inserted_at: now, updated_at: now],
	[name: "architectural manager", description: "", inserted_at: now, updated_at: now],
	[name: "archivist", description: "", inserted_at: now, updated_at: now],
	[name: "art director", description: "", inserted_at: now, updated_at: now],
	[name: "art teacher", description: "", inserted_at: now, updated_at: now],
	[name: "artist", description: "", inserted_at: now, updated_at: now],
	[name: "assembler", description: "", inserted_at: now, updated_at: now],
	[name: "astronomer", description: "", inserted_at: now, updated_at: now],
	[name: "athlete", description: "", inserted_at: now, updated_at: now],
	[name: "athletic trainer", description: "", inserted_at: now, updated_at: now],
	[name: "ATM machine repairer", description: "", inserted_at: now, updated_at: now],
	[name: "atmospheric scientist", description: "", inserted_at: now, updated_at: now],
	[name: "attendant", description: "", inserted_at: now, updated_at: now],
	[name:  "audio and video equipment technician", description: "", inserted_at: now, updated_at: now],
	[name:  "audio-visual and multimedia collections specialist", description: "", inserted_at: now, updated_at: now],
	[name:  "audiologist", description: "", inserted_at: now, updated_at: now],
	[name:  "auditor", description: "", inserted_at: now, updated_at: now],
	[name:  "author", description: "", inserted_at: now, updated_at: now],
	[name:  "auto damage insurance appraiser", description: "", inserted_at: now, updated_at: now],
	[name:  "automotive and watercraft service attendant", description: "", inserted_at: now, updated_at: now],
	[name:  "automotive glass installer", description: "", inserted_at: now, updated_at: now],
	[name:  "automotive mechanic", description: "", inserted_at: now, updated_at: now],
	[name:  "avionics technician", description: "", inserted_at: now, updated_at: now],
	[name: "baggage porter", description: "", inserted_at: now, updated_at: now],
	[name: "bailiff", description: "", inserted_at: now, updated_at: now],
	[name: "baker", description: "", inserted_at: now, updated_at: now],
	[name: "barback", description: "", inserted_at: now, updated_at: now],
	[name: "barber", description: "", inserted_at: now, updated_at: now],
	[name: "bartender", description: "", inserted_at: now, updated_at: now],
	[name: "basic education teacher", description: "", inserted_at: now, updated_at: now],
	[name: "behavioral disorder counselor", description: "", inserted_at: now, updated_at: now],
	[name: "bellhop", description: "", inserted_at: now, updated_at: now],
	[name: "bench carpenter", description: "", inserted_at: now, updated_at: now],
	[name: "bicycle repairer", description: "", inserted_at: now, updated_at: now],
	[name: "bill and account collector", description: "", inserted_at: now, updated_at: now],
	[name: "billing and posting clerk", description: "", inserted_at: now, updated_at: now],
	[name: "biochemist", description: "", inserted_at: now, updated_at: now],
	[name: "biological technician", description: "", inserted_at: now, updated_at: now],
	[name: "biomedical engineer", description: "", inserted_at: now, updated_at: now],
	[name: "biophysicist", description: "", inserted_at: now, updated_at: now],
	[name: "blaster", description: "", inserted_at: now, updated_at: now],
	[name: "blending machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "blockmason", description: "", inserted_at: now, updated_at: now],
	[name: "boiler operator", description: "", inserted_at: now, updated_at: now],
	[name: "boilermaker", description: "", inserted_at: now, updated_at: now],
	[name: "bookkeeper", description: "", inserted_at: now, updated_at: now],
	[name: "boring machine tool tender", description: "", inserted_at: now, updated_at: now],
	[name: "brazer", description: "", inserted_at: now, updated_at: now],
	[name: "brickmason", description: "", inserted_at: now, updated_at: now],
	[name: "bridge and lock tender", description: "", inserted_at: now, updated_at: now],
	[name: "broadcast news analyst", description: "", inserted_at: now, updated_at: now],
	[name: "broadcast technician", description: "", inserted_at: now, updated_at: now],
	[name: "brokerage clerk", description: "", inserted_at: now, updated_at: now],
	[name: "budget analyst", description: "", inserted_at: now, updated_at: now],
	[name: "building inspector", description: "", inserted_at: now, updated_at: now],
	[name: "bus mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "butcher", description: "", inserted_at: now, updated_at: now],
	[name: "buyer", description: "", inserted_at: now, updated_at: now],
	[name: "cabinetmaker", description: "", inserted_at: now, updated_at: now],
	[name: "cafeteria attendant", description: "", inserted_at: now, updated_at: now],
	[name: "cafeteria cook", description: "", inserted_at: now, updated_at: now],
	[name: "camera operator", description: "", inserted_at: now, updated_at: now],
	[name: "camera repairer", description: "", inserted_at: now, updated_at: now],
	[name: "cardiovascular technician", description: "", inserted_at: now, updated_at: now],
	[name: "cargo agent", description: "", inserted_at: now, updated_at: now],
	[name: "carpenter", description: "", inserted_at: now, updated_at: now],
	[name: "carpet installer", description: "", inserted_at: now, updated_at: now],
	[name: "cartographer", description: "", inserted_at: now, updated_at: now],
	[name: "cashier", description: "", inserted_at: now, updated_at: now],
	[name: "caster", description: "", inserted_at: now, updated_at: now],
	[name: "ceiling tile installer", description: "", inserted_at: now, updated_at: now],
	[name: "cellular equipment installer", description: "", inserted_at: now, updated_at: now],
	[name: "cement mason", description: "", inserted_at: now, updated_at: now],
	[name: "channeling machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "chauffeur", description: "", inserted_at: now, updated_at: now],
	[name: "checker", description: "", inserted_at: now, updated_at: now],
	[name: "chef", description: "", inserted_at: now, updated_at: now],
	[name: "chemical engineer", description: "", inserted_at: now, updated_at: now],
	[name: "chemical plant operator", description: "", inserted_at: now, updated_at: now],
	[name: "chemist", description: "", inserted_at: now, updated_at: now],
	[name: "chemistry teacher", description: "", inserted_at: now, updated_at: now],
	[name: "chief executive", description: "", inserted_at: now, updated_at: now],
	[name: "child social worker", description: "", inserted_at: now, updated_at: now],
	[name: "childcare worker", description: "", inserted_at: now, updated_at: now],
	[name: "chiropractor", description: "", inserted_at: now, updated_at: now],
	[name: "choreographer", description: "", inserted_at: now, updated_at: now],
	[name: "civil drafter", description: "", inserted_at: now, updated_at: now],
	[name: "civil engineer", description: "", inserted_at: now, updated_at: now],
	[name: "civil engineering technician", description: "", inserted_at: now, updated_at: now],
	[name: "claims adjuster", description: "", inserted_at: now, updated_at: now],
	[name: "claims examiner", description: "", inserted_at: now, updated_at: now],
	[name: "claims investigator", description: "", inserted_at: now, updated_at: now],
	[name: "cleaner", description: "", inserted_at: now, updated_at: now],
	[name: "clinical laboratory technician", description: "", inserted_at: now, updated_at: now],
	[name: "clinical laboratory technologist", description: "", inserted_at: now, updated_at: now],
	[name: "clinical psychologist", description: "", inserted_at: now, updated_at: now],
	[name: "coating worker", description: "", inserted_at: now, updated_at: now],
	[name: "coatroom attendant", description: "", inserted_at: now, updated_at: now],
	[name: "coil finisher", description: "", inserted_at: now, updated_at: now],
	[name: "coil taper", description: "", inserted_at: now, updated_at: now],
	[name: "coil winder", description: "", inserted_at: now, updated_at: now],
	[name: "coin machine servicer", description: "", inserted_at: now, updated_at: now],
	[name: "commercial diver", description: "", inserted_at: now, updated_at: now],
	[name: "commercial pilot", description: "", inserted_at: now, updated_at: now],
	[name: "commodities sales agent", description: "", inserted_at: now, updated_at: now],
	[name: "communications equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "communications teacher", description: "", inserted_at: now, updated_at: now],
	[name: "community association manager", description: "", inserted_at: now, updated_at: now],
	[name: "community service manager", description: "", inserted_at: now, updated_at: now],
	[name: "compensation and benefits manager", description: "", inserted_at: now, updated_at: now],
	[name: "compliance officer", description: "", inserted_at: now, updated_at: now],
	[name: "composer", description: "", inserted_at: now, updated_at: now],
	[name: "computer hardware engineer", description: "", inserted_at: now, updated_at: now],
	[name: "computer network architect", description: "", inserted_at: now, updated_at: now],
	[name: "computer operator", description: "", inserted_at: now, updated_at: now],
	[name: "computer programmer", description: "", inserted_at: now, updated_at: now],
	[name: "computer science teacher", description: "", inserted_at: now, updated_at: now],
	[name: "computer support specialist", description: "", inserted_at: now, updated_at: now],
	[name: "computer systems administrator", description: "", inserted_at: now, updated_at: now],
	[name: "computer systems analyst", description: "", inserted_at: now, updated_at: now],
	[name: "concierge", description: "", inserted_at: now, updated_at: now],
	[name: "conciliator", description: "", inserted_at: now, updated_at: now],
	[name: "concrete finisher", description: "", inserted_at: now, updated_at: now],
	[name: "conservation science teacher", description: "", inserted_at: now, updated_at: now],
	[name: "conservation scientist", description: "", inserted_at: now, updated_at: now],
	[name: "conservation worker", description: "", inserted_at: now, updated_at: now],
	[name: "conservator", description: "", inserted_at: now, updated_at: now],
	[name: "construction inspector", description: "", inserted_at: now, updated_at: now],
	[name: "construction manager", description: "", inserted_at: now, updated_at: now],
	[name: "construction painter", description: "", inserted_at: now, updated_at: now],
	[name: "construction worker", description: "", inserted_at: now, updated_at: now],
	[name: "continuous mining machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "convention planner", description: "", inserted_at: now, updated_at: now],
	[name: "conveyor operator", description: "", inserted_at: now, updated_at: now],
	[name: "cook", description: "", inserted_at: now, updated_at: now],
	[name: "cooling equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "copy marker", description: "", inserted_at: now, updated_at: now],
	[name: "correctional officer", description: "", inserted_at: now, updated_at: now],
	[name: "correctional treatment specialist", description: "", inserted_at: now, updated_at: now],
	[name: "correspondence clerk", description: "", inserted_at: now, updated_at: now],
	[name: "correspondent", description: "", inserted_at: now, updated_at: now],
	[name: "cosmetologist", description: "", inserted_at: now, updated_at: now],
	[name: "cost estimator", description: "", inserted_at: now, updated_at: now],
	[name: "costume attendant", description: "", inserted_at: now, updated_at: now],
	[name: "counseling psychologist", description: "", inserted_at: now, updated_at: now],
	[name: "counselor", description: "", inserted_at: now, updated_at: now],
	[name: "courier", description: "", inserted_at: now, updated_at: now],
	[name: "court reporter", description: "", inserted_at: now, updated_at: now],
	[name: "craft artist", description: "", inserted_at: now, updated_at: now],
	[name: "crane operator", description: "", inserted_at: now, updated_at: now],
	[name: "credit analyst", description: "", inserted_at: now, updated_at: now],
	[name: "credit checker", description: "", inserted_at: now, updated_at: now],
	[name: "credit counselor", description: "", inserted_at: now, updated_at: now],
	[name: "criminal investigator", description: "", inserted_at: now, updated_at: now],
	[name: "criminal justice teacher", description: "", inserted_at: now, updated_at: now],
	[name: "crossing guard", description: "", inserted_at: now, updated_at: now],
	[name: "curator", description: "", inserted_at: now, updated_at: now],
	[name: "custom sewer", description: "", inserted_at: now, updated_at: now],
	[name: "customer service representative", description: "", inserted_at: now, updated_at: now],
	[name: "cutter", description: "", inserted_at: now, updated_at: now],
	[name: "cutting machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "dancer", description: "", inserted_at: now, updated_at: now],
	[name: "data entry keyer", description: "", inserted_at: now, updated_at: now],
	[name: "database administrator", description: "", inserted_at: now, updated_at: now],
	[name: "decorating worker", description: "", inserted_at: now, updated_at: now],
	[name: "delivery services driver", description: "", inserted_at: now, updated_at: now],
	[name: "demonstrator", description: "", inserted_at: now, updated_at: now],
	[name: "dental assistant", description: "", inserted_at: now, updated_at: now],
	[name: "dental hygienist", description: "", inserted_at: now, updated_at: now],
	[name: "dental laboratory technician", description: "", inserted_at: now, updated_at: now],
	[name:  "dentist", description: "", inserted_at: now, updated_at: now],
	[name:  "derrick operator", description: "", inserted_at: now, updated_at: now],
	[name:  "designer", description: "", inserted_at: now, updated_at: now],
	[name:  "desktop publisher", description: "", inserted_at: now, updated_at: now],
	[name:  "detective", description: "", inserted_at: now, updated_at: now],
	[name:  "diagnostic medical sonographer", description: "", inserted_at: now, updated_at: now],
	[name:  "die maker", description: "", inserted_at: now, updated_at: now],
	[name:  "diesel engine specialist", description: "", inserted_at: now, updated_at: now],
	[name:  "dietetic technician", description: "", inserted_at: now, updated_at: now],
	[name:  "dietitian", description: "", inserted_at: now, updated_at: now],
	[name:  "dinkey operator", description: "", inserted_at: now, updated_at: now],
	[name:  "director", description: "", inserted_at: now, updated_at: now],
	[name:  "dishwasher", description: "", inserted_at: now, updated_at: now],
	[name:  "dispatcher", description: "", inserted_at: now, updated_at: now],
	[name:  "door-to-door sales worker", description: "", inserted_at: now, updated_at: now],
	[name:  "drafter", description: "", inserted_at: now, updated_at: now],
	[name:  "dragline operator", description: "", inserted_at: now, updated_at: now],
	[name:  "drama teacher", description: "", inserted_at: now, updated_at: now],
	[name:  "dredge operator", description: "", inserted_at: now, updated_at: now],
	[name:  "dressing room attendant", description: "", inserted_at: now, updated_at: now],
	[name:  "dressmaker", description: "", inserted_at: now, updated_at: now],
	[name:  "drier operator", description: "", inserted_at: now, updated_at: now],
	[name:  "drilling machine tool operator", description: "", inserted_at: now, updated_at: now],
	[name:  "dry-cleaning worker", description: "", inserted_at: now, updated_at: now],
	[name:  "drywall installer", description: "", inserted_at: now, updated_at: now],
	[name:  "dyeing machine operator", description: "", inserted_at: now, updated_at: now],
	[name:  "earth driller", description: "", inserted_at: now, updated_at: now],
	[name:  "economics teacher", description: "", inserted_at: now, updated_at: now],
	[name:  "economist", description: "", inserted_at: now, updated_at: now],
	[name:  "editor", description: "", inserted_at: now, updated_at: now],
	[name:  "education administrator", description: "", inserted_at: now, updated_at: now],
	[name:  "electric motor repairer", description: "", inserted_at: now, updated_at: now],
	[name:  "electrical electronics drafter", description: "", inserted_at: now, updated_at: now],
	[name:  "electrical engineer", description: "", inserted_at: now, updated_at: now],
	[name:  "electrical equipment assembler", description: "", inserted_at: now, updated_at: now],
	[name:  "electrical installer", description: "", inserted_at: now, updated_at: now],
	[name:  "electrical power-line installer", description: "", inserted_at: now, updated_at: now],
	[name:  "electrician", description: "", inserted_at: now, updated_at: now],
	[name:  "electro-mechanical technician", description: "", inserted_at: now, updated_at: now],
	[name:  "elementary school teacher", description: "", inserted_at: now, updated_at: now],
	[name:  "elevator installer", description: "", inserted_at: now, updated_at: now],
	[name:  "elevator repairer", description: "", inserted_at: now, updated_at: now],
	[name: "embalmer", description: "", inserted_at: now, updated_at: now],
	[name: "emergency management director", description: "", inserted_at: now, updated_at: now],
	[name: "emergency medical technician", description: "", inserted_at: now, updated_at: now],
	[name: "engine assembler", description: "", inserted_at: now, updated_at: now],
	[name: "engineer", description: "", inserted_at: now, updated_at: now],
	[name: "engineering manager", description: "", inserted_at: now, updated_at: now],
	[name: "engineering teacher", description: "", inserted_at: now, updated_at: now],
	[name: "english language teacher", description: "", inserted_at: now, updated_at: now],
	[name: "engraver", description: "", inserted_at: now, updated_at: now],
	[name: "entertainment attendant", description: "", inserted_at: now, updated_at: now],
	[name: "environmental engineer", description: "", inserted_at: now, updated_at: now],
	[name: "environmental science teacher", description: "", inserted_at: now, updated_at: now],
	[name: "environmental scientist", description: "", inserted_at: now, updated_at: now],
	[name: "epidemiologist", description: "", inserted_at: now, updated_at: now],
	[name: "escort", description: "", inserted_at: now, updated_at: now],
	[name: "etcher", description: "", inserted_at: now, updated_at: now],
	[name: "event planner", description: "", inserted_at: now, updated_at: now],
	[name: "excavating operator", description: "", inserted_at: now, updated_at: now],
	[name: "executive administrative assistant", description: "", inserted_at: now, updated_at: now],
	[name: "executive secretary", description: "", inserted_at: now, updated_at: now],
	[name: "exhibit designer", description: "", inserted_at: now, updated_at: now],
	[name: "expediting clerk", description: "", inserted_at: now, updated_at: now],
	[name: "explosives worker", description: "", inserted_at: now, updated_at: now],
	[name: "extraction worker", description: "", inserted_at: now, updated_at: now],
	[name: "fabric mender", description: "", inserted_at: now, updated_at: now],
	[name: "fabric patternmaker", description: "", inserted_at: now, updated_at: now],
	[name: "fabricator", description: "", inserted_at: now, updated_at: now],
	[name: "faller", description: "", inserted_at: now, updated_at: now],
	[name: "family practitioner", description: "", inserted_at: now, updated_at: now],
	[name: "family social worker", description: "", inserted_at: now, updated_at: now],
	[name: "family therapist", description: "", inserted_at: now, updated_at: now],
	[name: "farm advisor", description: "", inserted_at: now, updated_at: now],
	[name: "farm equipment mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "farm labor contractor", description: "", inserted_at: now, updated_at: now],
	[name: "farmer", description: "", inserted_at: now, updated_at: now],
	[name: "farmworker", description: "", inserted_at: now, updated_at: now],
	[name: "fashion designer", description: "", inserted_at: now, updated_at: now],
	[name: "fast food cook", description: "", inserted_at: now, updated_at: now],
	[name: "fence erector", description: "", inserted_at: now, updated_at: now],
	[name: "fiberglass fabricator", description: "", inserted_at: now, updated_at: now],
	[name: "fiberglass laminator", description: "", inserted_at: now, updated_at: now],
	[name: "file clerk", description: "", inserted_at: now, updated_at: now],
	[name: "filling machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "film and video editor", description: "", inserted_at: now, updated_at: now],
	[name: "financial analyst", description: "", inserted_at: now, updated_at: now],
	[name: "financial examiner", description: "", inserted_at: now, updated_at: now],
	[name: "financial manager", description: "", inserted_at: now, updated_at: now],
	[name: "financial services sales agent", description: "", inserted_at: now, updated_at: now],
	[name: "fine artist", description: "", inserted_at: now, updated_at: now],
	[name: "fire alarm system installer", description: "", inserted_at: now, updated_at: now],
	[name: "fire dispatcher", description: "", inserted_at: now, updated_at: now],
	[name: "fire inspector", description: "", inserted_at: now, updated_at: now],
	[name: "fire investigator", description: "", inserted_at: now, updated_at: now],
	[name: "firefighter", description: "", inserted_at: now, updated_at: now],
	[name: "fish and game warden", description: "", inserted_at: now, updated_at: now],
	[name: "fish cutter", description: "", inserted_at: now, updated_at: now],
	[name: "fish trimmer", description: "", inserted_at: now, updated_at: now],
	[name: "fisher", description: "", inserted_at: now, updated_at: now],
	[name: "fitness studies teacher", description: "", inserted_at: now, updated_at: now],
	[name: "fitness trainer", description: "", inserted_at: now, updated_at: now],
	[name: "flight attendant", description: "", inserted_at: now, updated_at: now],
	[name: "floor finisher", description: "", inserted_at: now, updated_at: now],
	[name: "floor layer", description: "", inserted_at: now, updated_at: now],
	[name: "floor sander", description: "", inserted_at: now, updated_at: now],
	[name: "floral designer", description: "", inserted_at: now, updated_at: now],
	[name: "food batchmaker", description: "", inserted_at: now, updated_at: now],
	[name: "food cooking machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "food preparation worker", description: "", inserted_at: now, updated_at: now],
	[name: "food science technician", description: "", inserted_at: now, updated_at: now],
	[name: "food scientist", description: "", inserted_at: now, updated_at: now],
	[name: "food server", description: "", inserted_at: now, updated_at: now],
	[name: "food service manager", description: "", inserted_at: now, updated_at: now],
	[name: "food technologist", description: "", inserted_at: now, updated_at: now],
	[name: "foreign language teacher", description: "", inserted_at: now, updated_at: now],
	[name: "foreign literature teacher", description: "", inserted_at: now, updated_at: now],
	[name: "forensic science technician", description: "", inserted_at: now, updated_at: now],
	[name: "forest fire inspector", description: "", inserted_at: now, updated_at: now],
	[name: "forest fire prevention specialist", description: "", inserted_at: now, updated_at: now],
	[name: "forest worker", description: "", inserted_at: now, updated_at: now],
	[name: "forester", description: "", inserted_at: now, updated_at: now],
	[name: "forestry teacher", description: "", inserted_at: now, updated_at: now],
	[name: "forging machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "foundry coremaker", description: "", inserted_at: now, updated_at: now],
	[name: "freight agent", description: "", inserted_at: now, updated_at: now],
	[name: "freight mover", description: "", inserted_at: now, updated_at: now],
	[name: "fundraising manager", description: "", inserted_at: now, updated_at: now],
	[name: "funeral attendant", description: "", inserted_at: now, updated_at: now],
	[name: "funeral director", description: "", inserted_at: now, updated_at: now],
	[name: "funeral service manager", description: "", inserted_at: now, updated_at: now],
	[name: "furnace operator", description: "", inserted_at: now, updated_at: now],
	[name: "furnishings worker", description: "", inserted_at: now, updated_at: now],
	[name: "furniture finisher", description: "", inserted_at: now, updated_at: now],
	[name: "gaming booth cashier", description: "", inserted_at: now, updated_at: now],
	[name: "gaming cage worker", description: "", inserted_at: now, updated_at: now],
	[name: "gaming change person", description: "", inserted_at: now, updated_at: now],
	[name: "gaming dealer", description: "", inserted_at: now, updated_at: now],
	[name: "gaming investigator", description: "", inserted_at: now, updated_at: now],
	[name: "gaming manager", description: "", inserted_at: now, updated_at: now],
	[name: "gaming surveillance officer", description: "", inserted_at: now, updated_at: now],
	[name: "garment mender", description: "", inserted_at: now, updated_at: now],
	[name: "garment presser", description: "", inserted_at: now, updated_at: now],
	[name: "gas compressor", description: "", inserted_at: now, updated_at: now],
	[name: "gas plant operator", description: "", inserted_at: now, updated_at: now],
	[name: "gas pumping station operator", description: "", inserted_at: now, updated_at: now],
	[name: "general manager", description: "", inserted_at: now, updated_at: now],
	[name: "general practitioner", description: "", inserted_at: now, updated_at: now],
	[name: "geographer", description: "", inserted_at: now, updated_at: now],
	[name: "geography teacher", description: "", inserted_at: now, updated_at: now],
	[name: "geological engineer", description: "", inserted_at: now, updated_at: now],
	[name: "geological technician", description: "", inserted_at: now, updated_at: now],
	[name: "geoscientist", description: "", inserted_at: now, updated_at: now],
	[name: "glazier", description: "", inserted_at: now, updated_at: now],
	[name: "government program eligibility interviewer", description: "", inserted_at: now, updated_at: now],
	[name: "graduate teaching assistant", description: "", inserted_at: now, updated_at: now],
	[name: "graphic designer", description: "", inserted_at: now, updated_at: now],
	[name: "groundskeeper", description: "", inserted_at: now, updated_at: now],
	[name: "groundskeeping worker", description: "", inserted_at: now, updated_at: now],
	[name: "gynecologist", description: "", inserted_at: now, updated_at: now],
	[name: "hairdresser", description: "", inserted_at: now, updated_at: now],
	[name: "hairstylist", description: "", inserted_at: now, updated_at: now],
	[name: "hand grinding worker", description: "", inserted_at: now, updated_at: now],
	[name: "hand laborer", description: "", inserted_at: now, updated_at: now],
	[name: "hand packager", description: "", inserted_at: now, updated_at: now],
	[name: "hand packer", description: "", inserted_at: now, updated_at: now],
	[name: "hand polishing worker", description: "", inserted_at: now, updated_at: now],
	[name: "hand sewer", description: "", inserted_at: now, updated_at: now],
	[name: "hazardous materials removal worker", description: "", inserted_at: now, updated_at: now],
	[name: "head cook", description: "", inserted_at: now, updated_at: now],
	[name: "health and safety engineer", description: "", inserted_at: now, updated_at: now],
	[name: "health educator", description: "", inserted_at: now, updated_at: now],
	[name: "health information technician", description: "", inserted_at: now, updated_at: now],
	[name: "health services manager", description: "", inserted_at: now, updated_at: now],
	[name: "health specialties teacher", description: "", inserted_at: now, updated_at: now],
	[name: "healthcare social worker", description: "", inserted_at: now, updated_at: now],
	[name: "hearing officer", description: "", inserted_at: now, updated_at: now],
	[name: "heat treating equipment setter", description: "", inserted_at: now, updated_at: now],
	[name: "heating installer", description: "", inserted_at: now, updated_at: now],
	[name: "heating mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "heavy truck driver", description: "", inserted_at: now, updated_at: now],
	[name: "highway maintenance worker", description: "", inserted_at: now, updated_at: now],
	[name: "historian", description: "", inserted_at: now, updated_at: now],
	[name: "history teacher", description: "", inserted_at: now, updated_at: now],
	[name: "hoist and winch operator", description: "", inserted_at: now, updated_at: now],
	[name: "home appliance repairer", description: "", inserted_at: now, updated_at: now],
	[name: "home economics teacher", description: "", inserted_at: now, updated_at: now],
	[name: "home entertainment installer", description: "", inserted_at: now, updated_at: now],
	[name: "home health aide", description: "", inserted_at: now, updated_at: now],
	[name: "home management advisor", description: "", inserted_at: now, updated_at: now],
	[name: "host", description: "", inserted_at: now, updated_at: now],
	[name: "hostess", description: "", inserted_at: now, updated_at: now],
	[name: "hostler", description: "", inserted_at: now, updated_at: now],
	[name: "hotel desk clerk", description: "", inserted_at: now, updated_at: now],
	[name: "housekeeping cleaner", description: "", inserted_at: now, updated_at: now],
	[name: "human resources assistant", description: "", inserted_at: now, updated_at: now],
	[name: "human resources manager", description: "", inserted_at: now, updated_at: now],
	[name: "human service assistant", description: "", inserted_at: now, updated_at: now],
	[name: "hunter", description: "", inserted_at: now, updated_at: now],
	[name: "hydrologist", description: "", inserted_at: now, updated_at: now],
	[name: "illustrator", description: "", inserted_at: now, updated_at: now],
	[name: "industrial designer", description: "", inserted_at: now, updated_at: now],
	[name: "industrial engineer", description: "", inserted_at: now, updated_at: now],
	[name: "industrial engineering technician", description: "", inserted_at: now, updated_at: now],
	[name: "industrial machinery mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "industrial production manager", description: "", inserted_at: now, updated_at: now],
	[name: "industrial truck operator", description: "", inserted_at: now, updated_at: now],
	[name: "industrial-organizational psychologist", description: "", inserted_at: now, updated_at: now],
	[name: "information clerk", description: "", inserted_at: now, updated_at: now],
	[name: "information research scientist", description: "", inserted_at: now, updated_at: now],
	[name: "information security analyst", description: "", inserted_at: now, updated_at: now],
	[name: "information systems manager", description: "", inserted_at: now, updated_at: now],
	[name: "inspector", description: "", inserted_at: now, updated_at: now],
	[name: "instructional coordinator", description: "", inserted_at: now, updated_at: now],
	[name: "instructor", description: "", inserted_at: now, updated_at: now],
	[name: "insulation worker", description: "", inserted_at: now, updated_at: now],
	[name: "insurance claims clerk", description: "", inserted_at: now, updated_at: now],
	[name: "insurance sales agent", description: "", inserted_at: now, updated_at: now],
	[name: "insurance underwriter", description: "", inserted_at: now, updated_at: now],
	[name: "intercity bus driver", description: "", inserted_at: now, updated_at: now],
	[name: "interior designer", description: "", inserted_at: now, updated_at: now],
	[name: "internist", description: "", inserted_at: now, updated_at: now],
	[name: "interpreter", description: "", inserted_at: now, updated_at: now],
	[name: "interviewer", description: "", inserted_at: now, updated_at: now],
	[name: "investigator", description: "", inserted_at: now, updated_at: now],
	[name: "jailer", description: "", inserted_at: now, updated_at: now],
	[name: "janitor", description: "", inserted_at: now, updated_at: now],
	[name: "jeweler", description: "", inserted_at: now, updated_at: now],
	[name: "judge", description: "", inserted_at: now, updated_at: now],
	[name: "judicial law clerk", description: "", inserted_at: now, updated_at: now],
	[name: "kettle operator", description: "", inserted_at: now, updated_at: now],
	[name: "kiln operator", description: "", inserted_at: now, updated_at: now],
	[name: "kindergarten teacher", description: "", inserted_at: now, updated_at: now],
	[name: "laboratory animal caretaker", description: "", inserted_at: now, updated_at: now],
	[name: "landscape architect", description: "", inserted_at: now, updated_at: now],
	[name: "landscaping worker", description: "", inserted_at: now, updated_at: now],
	[name: "lathe setter", description: "", inserted_at: now, updated_at: now],
	[name: "laundry worker", description: "", inserted_at: now, updated_at: now],
	[name: "law enforcement teacher", description: "", inserted_at: now, updated_at: now],
	[name: "law teacher", description: "", inserted_at: now, updated_at: now],
	[name: "lawyer", description: "", inserted_at: now, updated_at: now],
	[name: "layout worker", description: "", inserted_at: now, updated_at: now],
	[name: "leather worker", description: "", inserted_at: now, updated_at: now],
	[name: "legal assistant", description: "", inserted_at: now, updated_at: now],
	[name: "legal secretary", description: "", inserted_at: now, updated_at: now],
	[name: "legislator", description: "", inserted_at: now, updated_at: now],
	[name: "librarian", description: "", inserted_at: now, updated_at: now],
	[name: "library assistant", description: "", inserted_at: now, updated_at: now],
	[name: "library science teacher", description: "", inserted_at: now, updated_at: now],
	[name: "library technician", description: "", inserted_at: now, updated_at: now],
	[name: "licensed practical nurse", description: "", inserted_at: now, updated_at: now],
	[name: "licensed vocational nurse", description: "", inserted_at: now, updated_at: now],
	[name: "life scientist", description: "", inserted_at: now, updated_at: now],
	[name: "lifeguard", description: "", inserted_at: now, updated_at: now],
	[name: "light truck driver", description: "", inserted_at: now, updated_at: now],
	[name: "line installer", description: "", inserted_at: now, updated_at: now],
	[name: "literacy teacher", description: "", inserted_at: now, updated_at: now],
	[name: "literature teacher", description: "", inserted_at: now, updated_at: now],
	[name: "loading machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "loan clerk", description: "", inserted_at: now, updated_at: now],
	[name: "loan interviewer", description: "", inserted_at: now, updated_at: now],
	[name: "loan officer", description: "", inserted_at: now, updated_at: now],
	[name: "lobby attendant", description: "", inserted_at: now, updated_at: now],
	[name: "locker room attendant", description: "", inserted_at: now, updated_at: now],
	[name: "locksmith", description: "", inserted_at: now, updated_at: now],
	[name: "locomotive engineer", description: "", inserted_at: now, updated_at: now],
	[name: "locomotive firer", description: "", inserted_at: now, updated_at: now],
	[name: "lodging manager", description: "", inserted_at: now, updated_at: now],
	[name: "log grader", description: "", inserted_at: now, updated_at: now],
	[name: "logging equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "logistician", description: "", inserted_at: now, updated_at: now],
	[name: "machine feeder", description: "", inserted_at: now, updated_at: now],
	[name: "machinist", description: "", inserted_at: now, updated_at: now],
	[name: "magistrate judge", description: "", inserted_at: now, updated_at: now],
	[name: "magistrate", description: "", inserted_at: now, updated_at: now],
	[name: "maid", description: "", inserted_at: now, updated_at: now],
	[name: "mail clerk", description: "", inserted_at: now, updated_at: now],
	[name: "mail machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "mail superintendent", description: "", inserted_at: now, updated_at: now],
	[name: "maintenance painter", description: "", inserted_at: now, updated_at: now],
	[name: "maintenance worker", description: "", inserted_at: now, updated_at: now],
	[name: "makeup artist", description: "", inserted_at: now, updated_at: now],
	[name: "management analyst", description: "", inserted_at: now, updated_at: now],
	[name: "manicurist", description: "", inserted_at: now, updated_at: now],
	[name: "manufactured building installer", description: "", inserted_at: now, updated_at: now],
	[name: "mapping technician", description: "", inserted_at: now, updated_at: now],
	[name: "marble setter", description: "", inserted_at: now, updated_at: now],
	[name: "marine engineer", description: "", inserted_at: now, updated_at: now],
	[name: "marine oiler", description: "", inserted_at: now, updated_at: now],
	[name: "market research analyst", description: "", inserted_at: now, updated_at: now],
	[name: "marketing manager", description: "", inserted_at: now, updated_at: now],
	[name: "marketing specialist", description: "", inserted_at: now, updated_at: now],
	[name:  "marriage therapist", description: "", inserted_at: now, updated_at: now],
	[name:  "massage therapist", description: "", inserted_at: now, updated_at: now],
	[name:  "material mover", description: "", inserted_at: now, updated_at: now],
	[name:  "materials engineer", description: "", inserted_at: now, updated_at: now],
	[name:  "materials scientist", description: "", inserted_at: now, updated_at: now],
	[name:  "mathematical science teacher", description: "", inserted_at: now, updated_at: now],
	[name:  "mathematical technician", description: "", inserted_at: now, updated_at: now],
	[name:  "mathematician", description: "", inserted_at: now, updated_at: now],
	[name:  "maxillofacial surgeon", description: "", inserted_at: now, updated_at: now],
	[name:  "measurer", description: "", inserted_at: now, updated_at: now],
	[name:  "meat cutter", description: "", inserted_at: now, updated_at: now],
	[name:  "meat packer", description: "", inserted_at: now, updated_at: now],
	[name:  "meat trimmer", description: "", inserted_at: now, updated_at: now],
	[name:  "mechanical door repairer", description: "", inserted_at: now, updated_at: now],
	[name:  "mechanical drafter", description: "", inserted_at: now, updated_at: now],
	[name:  "mechanical engineer", description: "", inserted_at: now, updated_at: now],
	[name:  "mechanical engineering technician", description: "", inserted_at: now, updated_at: now],
	[name:  "mediator", description: "", inserted_at: now, updated_at: now],
	[name:  "medical appliance technician", description: "", inserted_at: now, updated_at: now],
	[name:  "medical assistant", description: "", inserted_at: now, updated_at: now],
	[name:  "medical equipment preparer", description: "", inserted_at: now, updated_at: now],
	[name:  "medical equipment repairer", description: "", inserted_at: now, updated_at: now],
	[name:  "medical laboratory technician", description: "", inserted_at: now, updated_at: now],
	[name:  "medical laboratory technologist", description: "", inserted_at: now, updated_at: now],
	[name:  "medical records technician", description: "", inserted_at: now, updated_at: now],
	[name:  "medical scientist", description: "", inserted_at: now, updated_at: now],
	[name:  "medical secretary", description: "", inserted_at: now, updated_at: now],
	[name:  "medical services manager", description: "", inserted_at: now, updated_at: now],
	[name:  "medical transcriptionist", description: "", inserted_at: now, updated_at: now],
	[name:  "meeting planner", description: "", inserted_at: now, updated_at: now],
	[name:  "mental health counselor", description: "", inserted_at: now, updated_at: now],
	[name: "mental health social worker", description: "", inserted_at: now, updated_at: now],
	[name: "merchandise displayer", description: "", inserted_at: now, updated_at: now],
	[name: "messenger", description: "", inserted_at: now, updated_at: now],
	[name: "metal caster", description: "", inserted_at: now, updated_at: now],
	[name: "metal patternmaker", description: "", inserted_at: now, updated_at: now],
	[name: "metal pickling operator", description: "", inserted_at: now, updated_at: now],
	[name: "metal pourer", description: "", inserted_at: now, updated_at: now],
	[name: "metal worker", description: "", inserted_at: now, updated_at: now],
	[name: "metal-refining furnace operator", description: "", inserted_at: now, updated_at: now],
	[name: "metal-refining furnace tender", description: "", inserted_at: now, updated_at: now],
	[name: "meter reader", description: "", inserted_at: now, updated_at: now],
	[name: "microbiologist", description: "", inserted_at: now, updated_at: now],
	[name: "middle school teacher", description: "", inserted_at: now, updated_at: now],
	[name: "milling machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "millwright", description: "", inserted_at: now, updated_at: now],
	[name: "mine cutting machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "mine shuttle car operator", description: "", inserted_at: now, updated_at: now],
	[name: "mining engineer", description: "", inserted_at: now, updated_at: now],
	[name: "mining safety engineer", description: "", inserted_at: now, updated_at: now],
	[name: "mining safety inspector", description: "", inserted_at: now, updated_at: now],
	[name: "mining service unit operator", description: "", inserted_at: now, updated_at: now],
	[name: "mixing machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "mobile heavy equipment mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "mobile home installer", description: "", inserted_at: now, updated_at: now],
	[name: "model maker", description: "", inserted_at: now, updated_at: now],
	[name: "model", description: "", inserted_at: now, updated_at: now],
	[name: "molder", description: "", inserted_at: now, updated_at: now],
	[name: "mortician", description: "", inserted_at: now, updated_at: now],
	[name: "motel desk clerk", description: "", inserted_at: now, updated_at: now],
	[name: "motion picture projectionist", description: "", inserted_at: now, updated_at: now],
	[name: "motorboat mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "motorboat operator", description: "", inserted_at: now, updated_at: now],
	[name: "motorboat service technician", description: "", inserted_at: now, updated_at: now],
	[name: "motorcycle mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "multimedia artist", description: "", inserted_at: now, updated_at: now],
	[name: "museum technician", description: "", inserted_at: now, updated_at: now],
	[name: "music director", description: "", inserted_at: now, updated_at: now],
	[name: "music teacher", description: "", inserted_at: now, updated_at: now],
	[name: "musical instrument repairer", description: "", inserted_at: now, updated_at: now],
	[name: "musician", description: "", inserted_at: now, updated_at: now],
	[name: "natural sciences manager", description: "", inserted_at: now, updated_at: now],
	[name: "naval architect", description: "", inserted_at: now, updated_at: now],
	[name: "network systems administrator", description: "", inserted_at: now, updated_at: now],
	[name: "new accounts clerk", description: "", inserted_at: now, updated_at: now],
	[name: "news vendor", description: "", inserted_at: now, updated_at: now],
	[name: "nonfarm animal caretaker", description: "", inserted_at: now, updated_at: now],
	[name: "nuclear engineer", description: "", inserted_at: now, updated_at: now],
	[name: "nuclear medicine technologist", description: "", inserted_at: now, updated_at: now],
	[name: "nuclear power reactor operator", description: "", inserted_at: now, updated_at: now],
	[name: "nuclear technician", description: "", inserted_at: now, updated_at: now],
	[name: "nursing aide", description: "", inserted_at: now, updated_at: now],
	[name: "nursing instructor", description: "", inserted_at: now, updated_at: now],
	[name: "nursing teacher", description: "", inserted_at: now, updated_at: now],
	[name: "nutritionist", description: "", inserted_at: now, updated_at: now],
	[name: "obstetrician", description: "", inserted_at: now, updated_at: now],
	[name: "occupational health and safety specialist", description: "", inserted_at: now, updated_at: now],
	[name: "occupational health and safety technician", description: "", inserted_at: now, updated_at: now],
	[name: "occupational therapist", description: "", inserted_at: now, updated_at: now],
	[name: "occupational therapy aide", description: "", inserted_at: now, updated_at: now],
	[name: "occupational therapy assistant", description: "", inserted_at: now, updated_at: now],
	[name: "offbearer", description: "", inserted_at: now, updated_at: now],
	[name: "office clerk", description: "", inserted_at: now, updated_at: now],
	[name: "office machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "operating engineer", description: "", inserted_at: now, updated_at: now],
	[name: "operations manager", description: "", inserted_at: now, updated_at: now],
	[name: "operations research analyst", description: "", inserted_at: now, updated_at: now],
	[name: "ophthalmic laboratory technician", description: "", inserted_at: now, updated_at: now],
	[name: "optician", description: "", inserted_at: now, updated_at: now],
	[name: "optometrist", description: "", inserted_at: now, updated_at: now],
	[name: "oral surgeon", description: "", inserted_at: now, updated_at: now],
	[name: "order clerk", description: "", inserted_at: now, updated_at: now],
	[name: "order filler", description: "", inserted_at: now, updated_at: now],
	[name: "orderly", description: "", inserted_at: now, updated_at: now],
	[name: "ordnance handling expert", description: "", inserted_at: now, updated_at: now],
	[name: "orthodontist", description: "", inserted_at: now, updated_at: now],
	[name: "orthotist", description: "", inserted_at: now, updated_at: now],
	[name: "outdoor power equipment mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "oven operator", description: "", inserted_at: now, updated_at: now],
	[name: "packaging machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "painter ", description: "", inserted_at: now, updated_at: now],
	[name: "painting worker", description: "", inserted_at: now, updated_at: now],
	[name: "paper goods machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "paperhanger", description: "", inserted_at: now, updated_at: now],
	[name: "paralegal", description: "", inserted_at: now, updated_at: now],
	[name: "paramedic", description: "", inserted_at: now, updated_at: now],
	[name: "parking enforcement worker", description: "", inserted_at: now, updated_at: now],
	[name: "parking lot attendant", description: "", inserted_at: now, updated_at: now],
	[name: "parts salesperson", description: "", inserted_at: now, updated_at: now],
	[name: "paving equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "payroll clerk", description: "", inserted_at: now, updated_at: now],
	[name: "pediatrician", description: "", inserted_at: now, updated_at: now],
	[name: "pedicurist", description: "", inserted_at: now, updated_at: now],
	[name: "personal care aide", description: "", inserted_at: now, updated_at: now],
	[name: "personal chef", description: "", inserted_at: now, updated_at: now],
	[name: "personal financial advisor", description: "", inserted_at: now, updated_at: now],
	[name: "pest control worker", description: "", inserted_at: now, updated_at: now],
	[name: "pesticide applicator", description: "", inserted_at: now, updated_at: now],
	[name: "pesticide handler", description: "", inserted_at: now, updated_at: now],
	[name: "pesticide sprayer", description: "", inserted_at: now, updated_at: now],
	[name: "petroleum engineer", description: "", inserted_at: now, updated_at: now],
	[name: "petroleum gauger", description: "", inserted_at: now, updated_at: now],
	[name: "petroleum pump system operator", description: "", inserted_at: now, updated_at: now],
	[name: "petroleum refinery operator", description: "", inserted_at: now, updated_at: now],
	[name: "petroleum technician", description: "", inserted_at: now, updated_at: now],
	[name: "pharmacist", description: "", inserted_at: now, updated_at: now],
	[name: "pharmacy aide", description: "", inserted_at: now, updated_at: now],
	[name: "pharmacy technician", description: "", inserted_at: now, updated_at: now],
	[name: "philosophy teacher", description: "", inserted_at: now, updated_at: now],
	[name: "photogrammetrist", description: "", inserted_at: now, updated_at: now],
	[name: "photographer", description: "", inserted_at: now, updated_at: now],
	[name: "photographic process worker", description: "", inserted_at: now, updated_at: now],
	[name: "photographic processing machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "physical therapist aide", description: "", inserted_at: now, updated_at: now],
	[name: "physical therapist assistant", description: "", inserted_at: now, updated_at: now],
	[name: "physical therapist", description: "", inserted_at: now, updated_at: now],
	[name: "physician assistant", description: "", inserted_at: now, updated_at: now],
	[name: "physician", description: "", inserted_at: now, updated_at: now],
	[name: "physicist", description: "", inserted_at: now, updated_at: now],
	[name: "physics teacher", description: "", inserted_at: now, updated_at: now],
	[name: "pile-driver operator", description: "", inserted_at: now, updated_at: now],
	[name: "pipefitter", description: "", inserted_at: now, updated_at: now],
	[name: "pipelayer", description: "", inserted_at: now, updated_at: now],
	[name: "planing machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "planning clerk", description: "", inserted_at: now, updated_at: now],
	[name: "plant operator", description: "", inserted_at: now, updated_at: now],
	[name: "plant scientist", description: "", inserted_at: now, updated_at: now],
	[name: "plasterer", description: "", inserted_at: now, updated_at: now],
	[name: "plastic patternmaker", description: "", inserted_at: now, updated_at: now],
	[name: "plastic worker", description: "", inserted_at: now, updated_at: now],
	[name: "plumber", description: "", inserted_at: now, updated_at: now],
	[name: "podiatrist", description: "", inserted_at: now, updated_at: now],
	[name: "police dispatcher", description: "", inserted_at: now, updated_at: now],
	[name: "police officer", description: "", inserted_at: now, updated_at: now],
	[name: "policy processing clerk", description: "", inserted_at: now, updated_at: now],
	[name: "political science teacher", description: "", inserted_at: now, updated_at: now],
	[name: "political scientist", description: "", inserted_at: now, updated_at: now],
	[name: "postal service clerk", description: "", inserted_at: now, updated_at: now],
	[name: "postal service mail carrier", description: "", inserted_at: now, updated_at: now],
	[name: "postal service mail processing machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "postal service mail processor", description: "", inserted_at: now, updated_at: now],
	[name: "postal service mail sorter", description: "", inserted_at: now, updated_at: now],
	[name: "postmaster", description: "", inserted_at: now, updated_at: now],
	[name: "postsecondary teacher", description: "", inserted_at: now, updated_at: now],
	[name: "poultry cutter", description: "", inserted_at: now, updated_at: now],
	[name: "poultry trimmer", description: "", inserted_at: now, updated_at: now],
	[name: "power dispatcher", description: "", inserted_at: now, updated_at: now],
	[name: "power distributor", description: "", inserted_at: now, updated_at: now],
	[name: "power plant operator", description: "", inserted_at: now, updated_at: now],
	[name: "power tool repairer", description: "", inserted_at: now, updated_at: now],
	[name: "precious stone worker", description: "", inserted_at: now, updated_at: now],
	[name: "precision instrument repairer", description: "", inserted_at: now, updated_at: now],
	[name: "prepress technician", description: "", inserted_at: now, updated_at: now],
	[name: "preschool teacher", description: "", inserted_at: now, updated_at: now],
	[name: "priest", description: "", inserted_at: now, updated_at: now],
	[name: "print binding worker", description: "", inserted_at: now, updated_at: now],
	[name: "printing press operator", description: "", inserted_at: now, updated_at: now],
	[name: "private detective", description: "", inserted_at: now, updated_at: now],
	[name: "probation officer", description: "", inserted_at: now, updated_at: now],
	[name: "procurement clerk", description: "", inserted_at: now, updated_at: now],
	[name: "producer", description: "", inserted_at: now, updated_at: now],
	[name: "product promoter", description: "", inserted_at: now, updated_at: now],
	[name: "production clerk", description: "", inserted_at: now, updated_at: now],
	[name: "production occupation", description: "", inserted_at: now, updated_at: now],
	[name: "proofreader", description: "", inserted_at: now, updated_at: now],
	[name: "property manager", description: "", inserted_at: now, updated_at: now],
	[name: "prosthetist", description: "", inserted_at: now, updated_at: now],
	[name: "prosthodontist", description: "", inserted_at: now, updated_at: now],
	[name: "psychiatric aide", description: "", inserted_at: now, updated_at: now],
	[name: "psychiatric technician", description: "", inserted_at: now, updated_at: now],
	[name: "psychiatrist", description: "", inserted_at: now, updated_at: now],
	[name: "psychologist", description: "", inserted_at: now, updated_at: now],
	[name: "psychology teacher", description: "", inserted_at: now, updated_at: now],
	[name: "public relations manager", description: "", inserted_at: now, updated_at: now],
	[name: "public relations specialist", description: "", inserted_at: now, updated_at: now],
	[name: "pump operator", description: "", inserted_at: now, updated_at: now],
	[name: "purchasing agent", description: "", inserted_at: now, updated_at: now],
	[name: "purchasing manager", description: "", inserted_at: now, updated_at: now],
	[name: "radiation therapist", description: "", inserted_at: now, updated_at: now],
	[name: "radio announcer", description: "", inserted_at: now, updated_at: now],
	[name: "radio equipment installer", description: "", inserted_at: now, updated_at: now],
	[name: "radio operator", description: "", inserted_at: now, updated_at: now],
	[name: "radiologic technician", description: "", inserted_at: now, updated_at: now],
	[name: "radiologic technologist", description: "", inserted_at: now, updated_at: now],
	[name: "rail car repairer", description: "", inserted_at: now, updated_at: now],
	[name: "rail transportation worker", description: "", inserted_at: now, updated_at: now],
	[name: "rail yard engineer", description: "", inserted_at: now, updated_at: now],
	[name: "rail-track laying equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "railroad brake operator", description: "", inserted_at: now, updated_at: now],
	[name: "railroad conductor", description: "", inserted_at: now, updated_at: now],
	[name: "railroad police", description: "", inserted_at: now, updated_at: now],
	[name: "rancher", description: "", inserted_at: now, updated_at: now],
	[name: "real estate appraiser", description: "", inserted_at: now, updated_at: now],
	[name: "real estate broker", description: "", inserted_at: now, updated_at: now],
	[name: "real estate manager", description: "", inserted_at: now, updated_at: now],
	[name: "real estate sales agent", description: "", inserted_at: now, updated_at: now],
	[name: "receiving clerk", description: "", inserted_at: now, updated_at: now],
	[name: "receptionist", description: "", inserted_at: now, updated_at: now],
	[name: "record clerk", description: "", inserted_at: now, updated_at: now],
	[name: "recreation teacher", description: "", inserted_at: now, updated_at: now],
	[name: "recreation worker", description: "", inserted_at: now, updated_at: now],
	[name: "recreational therapist", description: "", inserted_at: now, updated_at: now],
	[name: "recreational vehicle service technician", description: "", inserted_at: now, updated_at: now],
	[name: "recyclable material collector", description: "", inserted_at: now, updated_at: now],
	[name: "referee", description: "", inserted_at: now, updated_at: now],
	[name: "refractory materials repairer", description: "", inserted_at: now, updated_at: now],
	[name: "refrigeration installer", description: "", inserted_at: now, updated_at: now],
	[name: "refrigeration mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "refuse collector", description: "", inserted_at: now, updated_at: now],
	[name: "regional planner", description: "", inserted_at: now, updated_at: now],
	[name: "registered nurse", description: "", inserted_at: now, updated_at: now],
	[name: "rehabilitation counselor", description: "", inserted_at: now, updated_at: now],
	[name: "reinforcing iron worker", description: "", inserted_at: now, updated_at: now],
	[name: "reinforcing rebar worker", description: "", inserted_at: now, updated_at: now],
	[name: "religion teacher", description: "", inserted_at: now, updated_at: now],
	[name: "religious activities director", description: "", inserted_at: now, updated_at: now],
	[name: "religious worker", description: "", inserted_at: now, updated_at: now],
	[name: "rental clerk", description: "", inserted_at: now, updated_at: now],
	[name: "repair worker", description: "", inserted_at: now, updated_at: now],
	[name: "reporter", description: "", inserted_at: now, updated_at: now],
	[name: "residential advisor", description: "", inserted_at: now, updated_at: now],
	[name: "resort desk clerk", description: "", inserted_at: now, updated_at: now],
	[name: "respiratory therapist", description: "", inserted_at: now, updated_at: now],
	[name: "respiratory therapy technician", description: "", inserted_at: now, updated_at: now],
	[name: "retail buyer", description: "", inserted_at: now, updated_at: now],
	[name: "retail salesperson", description: "", inserted_at: now, updated_at: now],
	[name: "revenue agent", description: "", inserted_at: now, updated_at: now],
	[name: "rigger", description: "", inserted_at: now, updated_at: now],
	[name: "rock splitter", description: "", inserted_at: now, updated_at: now],
	[name: "rolling machine tender", description: "", inserted_at: now, updated_at: now],
	[name: "roof bolter", description: "", inserted_at: now, updated_at: now],
	[name: "roofer", description: "", inserted_at: now, updated_at: now],
	[name: "rotary drill operator", description: "", inserted_at: now, updated_at: now],
	[name: "roustabout", description: "", inserted_at: now, updated_at: now],
	[name: "safe repairer", description: "", inserted_at: now, updated_at: now],
	[name: "sailor", description: "", inserted_at: now, updated_at: now],
	[name: "sales engineer", description: "", inserted_at: now, updated_at: now],
	[name: "sales manager", description: "", inserted_at: now, updated_at: now],
	[name: "sales representative", description: "", inserted_at: now, updated_at: now],
	[name: "sampler", description: "", inserted_at: now, updated_at: now],
	[name: "sawing machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "scaler", description: "", inserted_at: now, updated_at: now],
	[name: "school bus driver", description: "", inserted_at: now, updated_at: now],
	[name: "school psychologist", description: "", inserted_at: now, updated_at: now],
	[name: "school social worker", description: "", inserted_at: now, updated_at: now],
	[name: "scout leader", description: "", inserted_at: now, updated_at: now],
	[name: "sculptor", description: "", inserted_at: now, updated_at: now],
	[name: "secondary education teacher", description: "", inserted_at: now, updated_at: now],
	[name: "secondary school teacher", description: "", inserted_at: now, updated_at: now],
	[name: "secretary", description: "", inserted_at: now, updated_at: now],
	[name: "securities sales agent", description: "", inserted_at: now, updated_at: now],
	[name: "security guard", description: "", inserted_at: now, updated_at: now],
	[name: "security system installer", description: "", inserted_at: now, updated_at: now],
	[name: "segmental paver", description: "", inserted_at: now, updated_at: now],
	[name: "self-enrichment education teacher", description: "", inserted_at: now, updated_at: now],
	[name: "semiconductor processor", description: "", inserted_at: now, updated_at: now],
	[name: "septic tank servicer", description: "", inserted_at: now, updated_at: now],
	[name: "set designer", description: "", inserted_at: now, updated_at: now],
	[name: "sewer pipe cleaner", description: "", inserted_at: now, updated_at: now],
	[name: "sewing machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "shampooer", description: "", inserted_at: now, updated_at: now],
	[name: "shaper", description: "", inserted_at: now, updated_at: now],
	[name: "sheet metal worker", description: "", inserted_at: now, updated_at: now],
	[name: "sheriff's patrol officer", description: "", inserted_at: now, updated_at: now],
	[name: "ship captain", description: "", inserted_at: now, updated_at: now],
	[name: "ship engineer", description: "", inserted_at: now, updated_at: now],
	[name: "ship loader", description: "", inserted_at: now, updated_at: now],
	[name: "shipmate", description: "", inserted_at: now, updated_at: now],
	[name: "shipping clerk", description: "", inserted_at: now, updated_at: now],
	[name: "shoe machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "shoe worker", description: "", inserted_at: now, updated_at: now],
	[name: "short order cook", description: "", inserted_at: now, updated_at: now],
	[name: "signal operator", description: "", inserted_at: now, updated_at: now],
	[name: "signal repairer", description: "", inserted_at: now, updated_at: now],
	[name: "singer", description: "", inserted_at: now, updated_at: now],
	[name: "ski patrol", description: "", inserted_at: now, updated_at: now],
	[name: "skincare specialist", description: "", inserted_at: now, updated_at: now],
	[name: "slaughterer", description: "", inserted_at: now, updated_at: now],
	[name: "slicing machine tender", description: "", inserted_at: now, updated_at: now],
	[name: "slot supervisor", description: "", inserted_at: now, updated_at: now],
	[name: "social science research assistant", description: "", inserted_at: now, updated_at: now],
	[name: "social sciences teacher", description: "", inserted_at: now, updated_at: now],
	[name: "social scientist", description: "", inserted_at: now, updated_at: now],
	[name: "social service assistant", description: "", inserted_at: now, updated_at: now],
	[name: "social service manager", description: "", inserted_at: now, updated_at: now],
	[name: "social work teacher", description: "", inserted_at: now, updated_at: now],
	[name: "social worker", description: "", inserted_at: now, updated_at: now],
	[name: "sociologist", description: "", inserted_at: now, updated_at: now],
	[name: "sociology teacher", description: "", inserted_at: now, updated_at: now],
	[name: "software developer", description: "", inserted_at: now, updated_at: now],
	[name: "software engineer", description: "", inserted_at: now, updated_at: now],
	[name: "soil scientist", description: "", inserted_at: now, updated_at: now],
	[name: "solderer", description: "", inserted_at: now, updated_at: now],
	[name: "sorter", description: "", inserted_at: now, updated_at: now],
	[name: "sound engineering technician", description: "", inserted_at: now, updated_at: now],
	[name: "space scientist", description: "", inserted_at: now, updated_at: now],
	[name: "special education teacher", description: "", inserted_at: now, updated_at: now],
	[name: "speech-language pathologist", description: "", inserted_at: now, updated_at: now],
	[name: "sports book runner", description: "", inserted_at: now, updated_at: now],
	[name: "sports entertainer", description: "", inserted_at: now, updated_at: now],
	[name: "sports performer", description: "", inserted_at: now, updated_at: now],
	[name: "stationary engineer", description: "", inserted_at: now, updated_at: now],
	[name: "statistical assistant", description: "", inserted_at: now, updated_at: now],
	[name: "statistician", description: "", inserted_at: now, updated_at: now],
	[name: "steamfitter", description: "", inserted_at: now, updated_at: now],
	[name: "stock clerk", description: "", inserted_at: now, updated_at: now],
	[name: "stock mover", description: "", inserted_at: now, updated_at: now],
	[name: "stonemason", description: "", inserted_at: now, updated_at: now],
	[name: "street vendor", description: "", inserted_at: now, updated_at: now],
	[name: "streetcar operator", description: "", inserted_at: now, updated_at: now],
	[name: "structural iron worker", description: "", inserted_at: now, updated_at: now],
	[name: "structural metal fabricator", description: "", inserted_at: now, updated_at: now],
	[name: "structural metal fitter", description: "", inserted_at: now, updated_at: now],
	[name: "structural steel worker", description: "", inserted_at: now, updated_at: now],
	[name: "stucco mason", description: "", inserted_at: now, updated_at: now],
	[name: "substance abuse counselor", description: "", inserted_at: now, updated_at: now],
	[name: "substance abuse social worker", description: "", inserted_at: now, updated_at: now],
	[name: "subway operator", description: "", inserted_at: now, updated_at: now],
	[name: "surfacing equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "surgeon", description: "", inserted_at: now, updated_at: now],
	[name: "surgical technologist", description: "", inserted_at: now, updated_at: now],
	[name: "survey researcher", description: "", inserted_at: now, updated_at: now],
	[name: "surveying technician", description: "", inserted_at: now, updated_at: now],
	[name: "surveyor", description: "", inserted_at: now, updated_at: now],
	[name: "switch operator", description: "", inserted_at: now, updated_at: now],
	[name: "switchboard operator", description: "", inserted_at: now, updated_at: now],
	[name: "tailor", description: "", inserted_at: now, updated_at: now],
	[name: "tamping equipment operator", description: "", inserted_at: now, updated_at: now],
	[name: "tank car loader", description: "", inserted_at: now, updated_at: now],
	[name: "taper", description: "", inserted_at: now, updated_at: now],
	[name: "tax collector", description: "", inserted_at: now, updated_at: now],
	[name: "tax examiner", description: "", inserted_at: now, updated_at: now],
	[name: "tax preparer", description: "", inserted_at: now, updated_at: now],
	[name: "taxi driver", description: "", inserted_at: now, updated_at: now],
	[name: "teacher assistant", description: "", inserted_at: now, updated_at: now],
	[name: "teacher", description: "", inserted_at: now, updated_at: now],
	[name: "team assembler", description: "", inserted_at: now, updated_at: now],
	[name: "technical writer", description: "", inserted_at: now, updated_at: now],
	[name: "telecommunications equipment installer", description: "", inserted_at: now, updated_at: now],
	[name: "telemarketer", description: "", inserted_at: now, updated_at: now],
	[name: "telephone operator", description: "", inserted_at: now, updated_at: now],
	[name: "television announcer", description: "", inserted_at: now, updated_at: now],
	[name: "teller", description: "", inserted_at: now, updated_at: now],
	[name: "terrazzo finisher", description: "", inserted_at: now, updated_at: now],
	[name: "terrazzo worker", description: "", inserted_at: now, updated_at: now],
	[name: "tester", description: "", inserted_at: now, updated_at: now],
	[name: "textile bleaching operator", description: "", inserted_at: now, updated_at: now],
	[name: "textile cutting machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "textile knitting machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "textile presser", description: "", inserted_at: now, updated_at: now],
	[name: "textile worker", description: "", inserted_at: now, updated_at: now],
	[name: "therapist", description: "", inserted_at: now, updated_at: now],
	[name: "ticket agent", description: "", inserted_at: now, updated_at: now],
	[name: "ticket taker", description: "", inserted_at: now, updated_at: now],
	[name: "tile setter", description: "", inserted_at: now, updated_at: now],
	[name: "timekeeping clerk", description: "", inserted_at: now, updated_at: now],
	[name: "timing device assembler", description: "", inserted_at: now, updated_at: now],
	[name: "tire builder", description: "", inserted_at: now, updated_at: now],
	[name: "tire changer", description: "", inserted_at: now, updated_at: now],
	[name: "tire repairer", description: "", inserted_at: now, updated_at: now],
	[name: "title abstractor", description: "", inserted_at: now, updated_at: now],
	[name: "title examiner", description: "", inserted_at: now, updated_at: now],
	[name: "title searcher", description: "", inserted_at: now, updated_at: now],
	[name: "tobacco roasting machine operator", description: "", inserted_at: now, updated_at: now],
	[name: "tool filer", description: "", inserted_at: now, updated_at: now],
	[name: "tool grinder", description: "", inserted_at: now, updated_at: now],
	[name: "tool maker", description: "", inserted_at: now, updated_at: now],
	[name: "tool sharpener", description: "", inserted_at: now, updated_at: now],
	[name: "tour guide", description: "", inserted_at: now, updated_at: now],
	[name: "tower equipment installer", description: "", inserted_at: now, updated_at: now],
	[name: "tower operator", description: "", inserted_at: now, updated_at: now],
	[name: "track switch repairer", description: "", inserted_at: now, updated_at: now],
	[name: "tractor operator", description: "", inserted_at: now, updated_at: now],
	[name: "tractor-trailer truck driver", description: "", inserted_at: now, updated_at: now],
	[name: "traffic clerk", description: "", inserted_at: now, updated_at: now],
	[name: "traffic technician", description: "", inserted_at: now, updated_at: now],
	[name: "training and development manager", description: "", inserted_at: now, updated_at: now],
	[name: "training and development specialist", description: "", inserted_at: now, updated_at: now],
	[name: "transit police", description: "", inserted_at: now, updated_at: now],
	[name: "translator", description: "", inserted_at: now, updated_at: now],
	[name: "transportation equipment painter", description: "", inserted_at: now, updated_at: now],
	[name: "transportation inspector", description: "", inserted_at: now, updated_at: now],
	[name: "transportation security screener", description: "", inserted_at: now, updated_at: now],
	[name: "transportation worker", description: "", inserted_at: now, updated_at: now],
	[name: "trapper", description: "", inserted_at: now, updated_at: now],
	[name: "travel agent", description: "", inserted_at: now, updated_at: now],
	[name: "travel clerk", description: "", inserted_at: now, updated_at: now],
	[name: "travel guide", description: "", inserted_at: now, updated_at: now],
	[name: "tree pruner", description: "", inserted_at: now, updated_at: now],
	[name: "tree trimmer", description: "", inserted_at: now, updated_at: now],
	[name: "trimmer", description: "", inserted_at: now, updated_at: now],
	[name: "truck loader", description: "", inserted_at: now, updated_at: now],
	[name: "truck mechanic", description: "", inserted_at: now, updated_at: now],
	[name: "tuner", description: "", inserted_at: now, updated_at: now],
	[name: "turning machine tool operator", description: "", inserted_at: now, updated_at: now],
	[name: "typist", description: "", inserted_at: now, updated_at: now],
	[name: "umpire", description: "", inserted_at: now, updated_at: now],
	[name: "undertaker", description: "", inserted_at: now, updated_at: now],
	[name: "upholsterer", description: "", inserted_at: now, updated_at: now],
	[name: "urban planner", description: "", inserted_at: now, updated_at: now],
	[name: "usher", description: "", inserted_at: now, updated_at: now],
	[name: "valve installer", description: "", inserted_at: now, updated_at: now],
	[name: "vending machine servicer", description: "", inserted_at: now, updated_at: now],
	[name: "veterinarian", description: "", inserted_at: now, updated_at: now],
	[name: "veterinary assistant", description: "", inserted_at: now, updated_at: now],
	[name: "veterinary technician", description: "", inserted_at: now, updated_at: now],
	[name: "vocational counselor", description: "", inserted_at: now, updated_at: now],
	[name: "vocational education teacher", description: "", inserted_at: now, updated_at: now],
	[name: "waiter", description: "", inserted_at: now, updated_at: now],
	[name: "waitress", description: "", inserted_at: now, updated_at: now],
	[name: "watch repairer", description: "", inserted_at: now, updated_at: now],
	[name: "water treatment plant operator", description: "", inserted_at: now, updated_at: now],
	[name: "weaving machine setter", description: "", inserted_at: now, updated_at: now],
	[name: "web developer", description: "", inserted_at: now, updated_at: now],
	[name: "weigher", description: "", inserted_at: now, updated_at: now],
	[name: "welder", description: "", inserted_at: now, updated_at: now],
	[name: "wellhead pumper", description: "", inserted_at: now, updated_at: now],
	[name: "wholesale buyer", description: "", inserted_at: now, updated_at: now],
	[name: "wildlife biologist", description: "", inserted_at: now, updated_at: now],
	[name: "window trimmer", description: "", inserted_at: now, updated_at: now],
	[name: "wood patternmaker", description: "", inserted_at: now, updated_at: now],
	[name: "woodworker", description: "", inserted_at: now, updated_at: now],
	[name: "word processor", description: "", inserted_at: now, updated_at: now],
	[name: "writer", description: "", inserted_at: now, updated_at: now],
	[name: "yardmasterm", description: "", inserted_at: now, updated_at: now],
	[name: "zoologist", description: "", inserted_at: now, updated_at: now]]
)
